version: '3'
services:
  nginx:
    image: nginx
    build: docker
    tty: true
    ports:
    - "8080:80"
  web1:
    image: node:15.5.1-alpine3.12
    working_dir: /app
    tty: true
    volumes:
      - ./api:/app
    command: yarn start
    # ports:
    #   - "3000:3000"
  web2:
    image: node:15.5.1-alpine3.12
    working_dir: /app
    tty: true
    volumes:
      - ./api:/app
    command: yarn start
  web3:
    image: node:15.5.1-alpine3.12
    working_dir: /app
    tty: true
    volumes:
      - ./api:/app
    command: yarn start